// <auto-generated />
using System;
using Inheritance_Mapping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inheritance_Mapping.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925112412_TPC Table Per Concrete Type migration")]
    partial class TPCTablePerConcreteTypemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inheritance_Mapping.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guest");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.FrequentGuest", b =>
                {
                    b.HasBaseType("Inheritance_Mapping.Models.Guest");

                    b.Property<DateTime>("LastStayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<int>("MembershipLevel")
                        .HasColumnType("int");

                    b.ToTable("FrequentGuests", (string)null);
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.VIPGuest", b =>
                {
                    b.HasBaseType("Inheritance_Mapping.Models.Guest");

                    b.Property<string>("VipCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("VIPGuests", (string)null);
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Reservation", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.Guest", "Guest")
                        .WithMany("Reservations")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.FrequentGuest", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.Guest", null)
                        .WithOne()
                        .HasForeignKey("Inheritance_Mapping.Models.FrequentGuest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.VIPGuest", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.Guest", null)
                        .WithOne()
                        .HasForeignKey("Inheritance_Mapping.Models.VIPGuest", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Guest", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
