// <auto-generated />
using System;
using Inheritance_Mapping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inheritance_Mapping.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250925090011_initailCreate")]
    partial class initailCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inheritance_Mapping.Models.Guest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");

                    b.HasDiscriminator().HasValue("Guest");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("GuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.FrequentGuest", b =>
                {
                    b.HasBaseType("Inheritance_Mapping.Models.Guest");

                    b.Property<DateTime>("LastStayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<int>("MembershipLevel")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("FrequentGuest");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.VIPGuest", b =>
                {
                    b.HasBaseType("Inheritance_Mapping.Models.Guest");

                    b.Property<string>("VipCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("VIPGuest");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Reservation", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.Guest", null)
                        .WithMany("reservations")
                        .HasForeignKey("GuestId");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Guest", b =>
                {
                    b.Navigation("reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
