// <auto-generated />
using System;
using Inheritance_Mapping.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TPC.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inheritance_Mapping.Models.FrequentGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastStayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<int>("MembershipLevel")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FrequentGuests", (string)null);
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FrequentGuestId")
                        .HasColumnType("int");

                    b.Property<int?>("VIPGuestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrequentGuestId");

                    b.HasIndex("VIPGuestId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.VIPGuest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VipCardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VIPGuests", (string)null);
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.Reservation", b =>
                {
                    b.HasOne("Inheritance_Mapping.Models.FrequentGuest", null)
                        .WithMany("reservations")
                        .HasForeignKey("FrequentGuestId");

                    b.HasOne("Inheritance_Mapping.Models.VIPGuest", null)
                        .WithMany("reservations")
                        .HasForeignKey("VIPGuestId");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.FrequentGuest", b =>
                {
                    b.Navigation("reservations");
                });

            modelBuilder.Entity("Inheritance_Mapping.Models.VIPGuest", b =>
                {
                    b.Navigation("reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
